# Exercice 1
Affichez les revenus du département "Provence-Alpes-Côte d'Azur " issus de la taxe CVAE des entreprises pour toutes les années (si plusieurs revenus CVAE existent pour une année donnée, vous devez additionner tous les revenus CVAE de cette année).
Vous devez utiliser un DataFrame Pandas.

In [1]:
import pandas as pd

In [2]:
doc=pd.read_csv("/home/vini/Downloads/mini-projet01/dataset.csv")
df=pd.DataFrame(doc)
df

,year,reg_name,tax_name,reg_id,tax_id,amount
0,2013,Provence-Alpes-Côte d'Azur,Charges financières,d2cc5169-137b-41a4-a683-91d94847ef98,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,67098706.61
1,2017,Provence-Alpes-Côte d'Azur,Charges financières,d2cc5169-137b-41a4-a683-91d94847ef98,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,79035112.44
2,2016,Provence-Alpes-Côte d'Azur,Charges financières,d2cc5169-137b-41a4-a683-91d94847ef98,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,76294679.54
3,2014,Provence-Alpes-Côte d'Azur,Charges financières,d2cc5169-137b-41a4-a683-91d94847ef98,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,73277233.05
4,2018,Provence-Alpes-Côte d'Azur,Charges financières,d2cc5169-137b-41a4-a683-91d94847ef98,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,85759999.44
...,...,...,...,...,...,...
9188,2016,Guyane,DDEC,52393301-f3ee-44ae-b9c7-7a2e546dd159,efa576f6-1593-46e3-b088-419eb1aac85c,4522722.00
9189,2017,Guyane,DDEC,52393301-f3ee-44ae-b9c7-7a2e546dd159,efa576f6-1593-46e3-b088-419eb1aac85c,4522722.00
9190,2019,Guyane,DDEC,52393301-f3ee-44ae-b9c7-7a2e546dd159,efa576f6-1593-46e3-b088-419eb1aac85c,4522722.00
9191,2018,Guyane,DDEC,52393301-f3ee-44ae-b9c7-7a2e546dd159,efa576f6-1593-46e3-b088-419eb1aac85c,4522722.00
9192,2019,La Réunion,DDEC,62512c29-eb2a-4d06-b9ea-34e78eae65f6,efa576f6-1593-46e3-b088-419eb1aac85c,0.00

In [3]:
df.loc[(df["reg_name"]== "Provence-Alpes-Côte d'Azur") & (df["tax_name"]=="CVAE")].groupby(["year"]).sum()

,reg_name,tax_name,reg_id,tax_id,amount
year,,,,,
2012,Provence-Alpes-Côte d'Azur,CVAE,d2cc5169-137b-41a4-a683-91d94847ef98,7c85096d-d549-426d-939d-a2339f0814c6,239731588.0
2013,Provence-Alpes-Côte d'Azur,CVAE,d2cc5169-137b-41a4-a683-91d94847ef98,7c85096d-d549-426d-939d-a2339f0814c6,258064116.0
2014,Provence-Alpes-Côte d'Azur,CVAE,d2cc5169-137b-41a4-a683-91d94847ef98,7c85096d-d549-426d-939d-a2339f0814c6,262012383.0
2015,Provence-Alpes-Côte d'Azur,CVAE,d2cc5169-137b-41a4-a683-91d94847ef98,7c85096d-d549-426d-939d-a2339f0814c6,266927276.0
2016,Provence-Alpes-Côte d'Azur,CVAE,d2cc5169-137b-41a4-a683-91d94847ef98,7c85096d-d549-426d-939d-a2339f0814c6,271297733.0
2017,Provence-Alpes-Côte d'Azur,CVAE,d2cc5169-137b-41a4-a683-91d94847ef98,7c85096d-d549-426d-939d-a2339f0814c6,563733303.0
2018,Provence-Alpes-Côte d'Azur,CVAE,d2cc5169-137b-41a4-a683-91d94847ef98,7c85096d-d549-426d-939d-a2339f0814c6,580056921.0
2019,Provence-Alpes-Côte d'Azur,CVAE,d2cc5169-137b-41a4-a683-91d94847ef98,7c85096d-d549-426d-939d-a2339f0814c6,629566622.0

Puisqu'il n'y a pas d'année qui se répertent le groupby ne fera pas de regroupement,donc pas de somme

  # Exercice 2
-Affichez les pays où les Dépenses d'investissement sont supérieures à la moyenne de chaque année.

-Affichez le nombre de region ayant les Dépenses d'investissement supérieur à la moyenne de chaque année

#Derterminons la moyenne de chaque année

In [4]:
moy_year=df.groupby(["year"]). amount.mean()
moy_year

year
2012    2.383688e+08
2013    2.456792e+08
2014    2.482317e+08
2015    2.595157e+08
2016    3.837655e+08
2017    4.162375e+08
2018    4.356039e+08
2019    4.493170e+08
Name: amount, dtype: float64

In [5]:
df.loc[df["reg_name"]>"moy_year"]

,year,reg_name,tax_name,reg_id,tax_id,amount
131,2015,Île-de-France,Charges financières,729fa8ca-e093-4744-83df-3481aaa9dc6d,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,123989908.3
132,2012,Île-de-France,Charges financières,729fa8ca-e093-4744-83df-3481aaa9dc6d,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,153642477.1
133,2019,Île-de-France,Charges financières,729fa8ca-e093-4744-83df-3481aaa9dc6d,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,125414307.0
134,2014,Île-de-France,Charges financières,729fa8ca-e093-4744-83df-3481aaa9dc6d,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,128777661.5
135,2016,Île-de-France,Charges financières,729fa8ca-e093-4744-83df-3481aaa9dc6d,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,122609318.1
...,...,...,...,...,...,...
9057,2012,Île-de-France,Encours de dette - Dépôts et cautionnements reçus,729fa8ca-e093-4744-83df-3481aaa9dc6d,dc6ec38c-df72-40a2-bb0d-730eb37da976,0.0
9058,2018,Île-de-France,Encours de dette - Dépôts et cautionnements reçus,729fa8ca-e093-4744-83df-3481aaa9dc6d,dc6ec38c-df72-40a2-bb0d-730eb37da976,0.0
9059,2019,Île-de-France,Encours de dette - Dépôts et cautionnements reçus,729fa8ca-e093-4744-83df-3481aaa9dc6d,dc6ec38c-df72-40a2-bb0d-730eb37da976,0.0
9060,2014,Île-de-France,Encours de dette - Dépôts et cautionnements reçus,729fa8ca-e093-4744-83df-3481aaa9dc6d,dc6ec38c-df72-40a2-bb0d-730eb37da976,0.0
9061,2015,Île-de-France,Encours de dette - Dépôts et cautionnements reçus,729fa8ca-e093-4744-83df-3481aaa9dc6d,dc6ec38c-df72-40a2-bb0d-730eb37da976,0.0

In [6]:
new_reg=df.loc[df["reg_name"]>"moy_year"].groupby("reg_name")
new_reg=df.groupby(["reg_name"]).amount.mean()
new_reg

reg_name
Auvergne-Rhône-Alpes          4.906079e+08
Bourgogne-Franche-Comté       1.836427e+08
Bretagne                      2.958220e+08
Centre-Val de Loire           2.489956e+08
Corse                         1.605598e+08
Grand Est                     2.873319e+08
Guadeloupe                    8.672538e+07
Guyane                        6.735773e+07
Hauts-de-France               4.458779e+08
La Réunion                    1.998330e+08
Martinique                    1.439732e+08
Normandie                     2.149605e+08
Nouvelle-Aquitaine            2.830110e+08
Occitanie                     3.849512e+08
Pays de la Loire              3.422371e+08
Provence-Alpes-Côte d'Azur    4.957370e+08
Île-de-France                 1.146040e+09
Name: amount, dtype: float64

In [7]:
df.loc[df["reg_name"]>"moy_year"].groupby(["reg_name"]).agg(sum)

,year,tax_name,reg_id,tax_id,amount
reg_name,,,,,
Île-de-France,858625,Charges financièresCharges financièresCharges ...,729fa8ca-e093-4744-83df-3481aaa9dc6d729fa8ca-e...,08a0eb61-f98d-4b6d-ba03-0e3c118c5da508a0eb61-f...,4.882132e+11

In [8]:
print(len(df.loc[df["reg_name"]>"moy_year"]))

426

# Exercice3
Faites la même chose que dans l'exercice 1, mais pour toutes les régions de France triées par les taxes pour toutes les années. À titre d'exemple, il s'agit d'un tableau croisé dynamique (pivot table) célèbre réalisé avec Excel

In [4]:
import pandas as pd

In [5]:
doc1=pd.read_csv("/home/vini/Downloads/mini-projet01/dataset.csv")
df=pd.DataFrame(doc1)
df

,year,reg_name,tax_name,reg_id,tax_id,amount
0,2013,Provence-Alpes-Côte d'Azur,Charges financières,d2cc5169-137b-41a4-a683-91d94847ef98,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,67098706.61
1,2017,Provence-Alpes-Côte d'Azur,Charges financières,d2cc5169-137b-41a4-a683-91d94847ef98,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,79035112.44
2,2016,Provence-Alpes-Côte d'Azur,Charges financières,d2cc5169-137b-41a4-a683-91d94847ef98,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,76294679.54
3,2014,Provence-Alpes-Côte d'Azur,Charges financières,d2cc5169-137b-41a4-a683-91d94847ef98,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,73277233.05
4,2018,Provence-Alpes-Côte d'Azur,Charges financières,d2cc5169-137b-41a4-a683-91d94847ef98,08a0eb61-f98d-4b6d-ba03-0e3c118c5da5,85759999.44
...,...,...,...,...,...,...
9188,2016,Guyane,DDEC,52393301-f3ee-44ae-b9c7-7a2e546dd159,efa576f6-1593-46e3-b088-419eb1aac85c,4522722.00
9189,2017,Guyane,DDEC,52393301-f3ee-44ae-b9c7-7a2e546dd159,efa576f6-1593-46e3-b088-419eb1aac85c,4522722.00
9190,2019,Guyane,DDEC,52393301-f3ee-44ae-b9c7-7a2e546dd159,efa576f6-1593-46e3-b088-419eb1aac85c,4522722.00
9191,2018,Guyane,DDEC,52393301-f3ee-44ae-b9c7-7a2e546dd159,efa576f6-1593-46e3-b088-419eb1aac85c,4522722.00
9192,2019,La Réunion,DDEC,62512c29-eb2a-4d06-b9ea-34e78eae65f6,efa576f6-1593-46e3-b088-419eb1aac85c,0.00

In [8]:

new_val= pd.pivot_table(df.index==["year","reg_name"],columns=['tax_name'])

ValueError: ('Lengths must match to compare', (9193,), (2,))